'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ChartNoAxesCombined, ChevronRight, CircleHelp, Layers3, LoaderCircle, ShieldCheck, SlidersHorizontal, Target, X } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarContent, SidebarFooter, SidebarHeader, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Choice, Pool, Settings, Conference } from '@/components/planning-controls';
import { Explorer } from '@/components/explorer';
import { Forecast, Results } from '@/components/results';
import { Scenarios } from '@/components/scenarios';
import { api, Bootstrap, Config, fmt, Job, Report, Validation } from '@/lib/model';

const NAV = [{id:'planner',label:'Schedule planner',icon:Layers3},{id:'explorer',label:'Opponent explorer',icon:Target},{id:'assumptions',label:'How the model works',icon:SlidersHorizontal}];

export default function Home() {
  const [data,setData]=useState<Bootstrap|null>(null);
  const [season,setSeason]=useState('2025');
  const [config,setConfig]=useState<Config|null>(null);
  const [report,setReport]=useState<Report|null>(null);
  const [view,setView]=useState('planner');
  const [error,setError]=useState('');
  const [validation,setValidation]=useState<Validation|null>(null);
  const [validationError,setValidationError]=useState('');
  const [selected,setSelected]=useState(0);
  const [job,setJob]=useState<Job|null>(null);
  const [starting,setStarting]=useState(false);
  const pendingConfig=useRef<Config|null>(null);
  const busy=starting||job?.status==='running'||job?.status==='cancelling';
  const stale=!!report&&JSON.stringify(config)!==JSON.stringify(report.config);
  const schedule=report?.top_schedules[selected];
  const fixedRecord=config?(['win','tie','loss'] as const).map(outcome=>config.fixed_games.filter(game=>game.result===outcome).length):[0,0,0];
  const fixedRate=config?.fixed_games.length?(fixedRecord[0]+fixedRecord[1]/2)/config.fixed_games.length:0;
  const leader=report?.top_schedules[0];
  const goalGap=leader?leader.projection.mean-leader.target_npi:null;

  useEffect(()=>{const abort=new AbortController();api<Bootstrap>(`bootstrap?season=${season}`,undefined,abort.signal).then(d=>{const loaded=pendingConfig.current?.season===season?pendingConfig.current:d.config;pendingConfig.current=null;setData(d);setConfig(loaded);setReport(loaded===d.config?d.report:null);setJob(null);setSelected(0);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[season]);
  useEffect(()=>{if(!config)return;const abort=new AbortController();setValidation(null);const timer=setTimeout(()=>api<Validation>('validate',config,abort.signal).then(v=>{setValidation(v);setValidationError('');}).catch(e=>{if(e.name!=='AbortError')setValidationError(e.message);}),200);return()=>{clearTimeout(timer);abort.abort();};},[config]);
  useEffect(()=>{
    if(!job?.id||!['running','cancelling'].includes(job.status))return;
    let disposed=false;let timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{try{const next=await api<Job>(`jobs/${job.id}`);if(disposed)return;setJob(next);if(next.status==='complete'&&next.report){setReport(next.report);setSelected(0);setError('');}else if(next.status==='error'){setError(next.message);}else if(['running','cancelling'].includes(next.status)){timer=setTimeout(poll,600);}}catch(e){if(disposed)return;const message=(e as Error).message;if(message.includes('not found')){setJob(null);setError('The app restarted and this comparison is no longer available. Your current inputs are still here.');}else{setError('The model connection was interrupted. Retrying; your inputs are unchanged.');timer=setTimeout(poll,2000);}}};
    timer=setTimeout(poll,200);return()=>{disposed=true;clearTimeout(timer);};
  },[job?.id,job?.status]);

  async function start(){if(!config||busy)throw new Error('A comparison is already running or inputs are not ready.');setStarting(true);setError('');try{const result=await api<{id:string}>('jobs',config);setJob({id:result.id,status:'running',message:'Preparing the full division…',progress:0,config});setView('planner');return result;}catch(e){setError((e as Error).message);throw e;}finally{setStarting(false);}}
  function cancel(){if(!job?.id||job.status!=='running')return;const current=job;setJob({...current,status:'cancelled',message:'Comparison cancelled. Your inputs are unchanged.'});void api<Job>(`jobs/${current.id}/cancel`,{}).catch(e=>setError((e as Error).message));}
  function changeSeason(next:string){setData(null);setValidation(null);setReport(null);setError('');setSeason(next);}
  function openScenario(next:Config){setReport(null);setJob(null);setSelected(0);setError('');setValidationError('');if(next.season!==season){pendingConfig.current=next;changeSeason(next.season);}else setConfig(next);setView('planner');}

  const heading=view==='planner'?['Build the best 5-game nonconference schedule.','Compare safer wins with tougher, higher-reward games while the NESCAC schedule stays fixed.']:view==='explorer'?['Test one opponent at a time.','See what a win, tie, or loss would do to Amherst’s projected season NPI.']:['How the model works','The calculation, historical data, and limits explained in plain English.'];
  return <SidebarProvider style={{'--sidebar-width':'226px'} as React.CSSProperties}>
    <Sidebar className="brand-sidebar"><SidebarHeader className="brand-head"><div className="brand-symbol"><ChartNoAxesCombined size={23}/></div><div><strong>Schedule Lab</strong><span>COLLEGIATE SOCCER</span></div></SidebarHeader><SidebarContent><div className="program"><div className="monogram">A</div><div><strong>Amherst</strong><span>Men’s soccer · Division III</span></div></div><p className="nav-label">WORKSPACE</p><SidebarMenu>{NAV.map(({id,label,icon:Icon})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>setView(id)}><Icon/><span>{label}</span>{view===id&&<ChevronRight className="ml-auto"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="verified"><ShieldCheck size={18}/><div><strong>{data?.source.rating_kind==='official_npi'?'Published NPI verified':'Historical reconstruction'}</strong><span>{data?`${data.teams.length} teams · ${data.source.season} data`:'Loading season data'}</span></div></div><div className="local-label"><span/>{data?.deployment?.hosted?'Hosted on Render':'Private, on this computer'}</div></SidebarFooter></Sidebar>
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-trigger"/><span>Workspace</span><ChevronRight size={14}/><strong>{NAV.find(n=>n.id===view)?.label}</strong></div><div className="season-control"><span>Historical season</span><Choice label="Historical season" value={season} disabled={busy} onChange={changeSeason} options={[{value:'2025',label:'2024–25 · Selection day'},{value:'2024',label:'2023–24 · Selection day'},{value:'2023',label:'2022–23 · Retrospective'},{value:'2022',label:'2021–22 · Retrospective'}]}/></div></header>
      <main className="main-content"><div className="page-heading"><div><p className="eyebrow">AMHERST MEN’S SOCCER</p><h1>{heading[0]}</h1><p>{heading[1]}</p></div>{view==='planner'&&config&&<div className="page-actions"><Scenarios config={config} onOpen={openScenario} disabled={busy}/><Button className="primary-action" disabled={!validation||busy} onClick={()=>void start().catch(()=>{})}>{busy?<><LoaderCircle size={17} className="spin"/>Comparing…</>:<>Compare {validation?.combinations??''} schedules<ArrowUpRight size={18}/></>}</Button></div>}</div>
      {error&&<div className="notice error" role="alert">{error}{!data&&<Button variant="outline" onClick={()=>window.location.reload()}>Reconnect</Button>}</div>}
      {!data||!config?<div className="loading-state"><LoaderCircle className="spin"/><h2>Connecting to the division model</h2><p>The verified historical data will appear here shortly.</p></div>:<>
        {job&&['running','cancelling'].includes(job.status)&&<div className="job-panel" role="status" aria-live="polite"><div><LoaderCircle size={18} className="spin"/><strong>{job.status==='cancelling'?'Stopping the comparison':`Recalculating all ${data.teams.length} teams`}</strong><Button variant="ghost" onClick={cancel}><X size={14}/>Cancel now</Button></div><Progress aria-label="Schedule comparison progress" value={job.progress*100}/><p>{job.message} You can keep using the app in another tab.</p></div>}
        {job?.status==='cancelled'&&<div className="notice neutral" role="status">Comparison cancelled. Your previous results and current inputs are unchanged.</div>}
        {view==='planner'&&<>{data.deployment?.hosted&&<div className="notice neutral">Shared link: use the Quick comparison while trying ideas. A more thorough final comparison can take several minutes.</div>}
          <div className="metrics goal-metrics"><div className="metric"><span>CONSERVATIVE NESCAC BASELINE</span><div>{fixedRate.toFixed(3).replace(/^0/,'')}<small>win rate</small></div><p>{fixedRecord[0]} wins · {fixedRecord[1]} ties · {fixedRecord[2]} losses</p></div><div className="metric"><span>NONCONFERENCE GAMES TO CHOOSE</span><div>{String(config.open_slots).padStart(2,'0')}<small>games</small></div><p>{validation?.candidate_count??'—'} teams in the pool · {config.required.length} required</p></div><div className="metric goal-metric"><label htmlFor="target-npi">TARGET SEASON NPI</label><div><input id="target-npi" className="goal-input" aria-label="Target season NPI" type="number" min="0" max="100" step="0.1" disabled={busy} value={config.target_npi} onChange={event=>{const value=event.currentTarget.valueAsNumber;if(Number.isFinite(value))setConfig({...config,target_npi:value});}}/><small>goal</small></div><p>Change this when the coach sets the final target</p></div><div className={`metric ${stale?'old-metric':''}`}><span>{stale?'PREVIOUS BEST ESTIMATE':'BEST PROJECTED NPI'}</span><div>{fmt(leader?.projection.mean)}<ArrowUpRight className="positive" size={22}/></div><p>{goalGap===null?'Compare schedules to see the goal gap':`${fmt(Math.abs(goalGap))} ${goalGap>=0?'above':'below'} the ${fmt(leader?.target_npi)} target`}</p></div></div>
          <section className="coach-guide" aria-label="How to use the schedule planner"><div><span>1</span><p><strong>Set the goal and baseline</strong>Use the target NPI and conservative NESCAC finish Coach described.</p></div><div><span>2</span><p><strong>Add matchup details</strong>Set each team’s priority, outlook, venue, dates, travel, and cost.</p></div><div><span>3</span><p><strong>Compare and save</strong>Review the strongest practical options, then save the plan to revisit it.</p></div></section>
          {stale&&<div className="stale-note" role="status"><CircleHelp size={16}/><span>Inputs have changed. The displayed projections belong to your previous comparison.</span></div>}
          <div className="planning-grid"><div className="main-stack"><Pool data={data} config={config} validation={validation} onChange={setConfig} disabled={busy}/><Conference config={config} data={data} onChange={setConfig} disabled={busy}/>{validationError&&<div className="notice error" role="alert">{validationError}</div>}</div><aside className="side-stack"><Settings config={config} onChange={setConfig} onReset={()=>{setConfig(data.config);setValidationError('');}} disabled={busy}/><Explorer config={config} data={data} compact/><Forecast schedule={schedule} stale={stale}/></aside></div>
          {report?<Results report={report} selected={selected} onSelect={setSelected} stale={stale}/>:<div className="panel empty-results"><ChartNoAxesCombined size={30}/><h2>Ready when you are</h2><p>Choose the teams Amherst could schedule, then compare the strongest 5-game combinations.</p></div>}
        </>}
        {view==='explorer'&&<><Explorer config={config} data={data}/><div className="explorer-bottom"><Conference config={config} data={data} onChange={setConfig} disabled={busy}/><div className="panel teaching-note"><CircleHelp size={22}/><div><h3>Why can a win hurt?</h3><p>Below ten retained win-equivalents, a low-value win still counts and can lower the average. Once the minimum is met, a weak additional win can be excluded. That’s why the same opponent can help one slate and hurt another.</p></div></div></div></>}
        {view==='assumptions'&&<ModelNotes data={data} config={config} onChange={setConfig} onReset={()=>setConfig(data.config)} disabled={busy}/>}
      </>}
      </main><footer className="app-footer">NPI Schedule Lab<span>Historical reference · Full-precision calculations · {data?.deployment?.hosted?'Hosted on Render':'Local only'}</span></footer>
    </div>
  </SidebarProvider>;
}

function ModelNotes({data,config,onChange,onReset,disabled}:{data:Bootstrap;config:Config;onChange:(c:Config)=>void;onReset:()=>void;disabled:boolean}){
  const official=data.source.rating_kind==='official_npi'; const team=data.teams.find(t=>t.name===config.target_team);
  return <div className="model-grid"><div className="main-stack"><section className="panel model-card"><div className="panel-heading"><h2>What happens when you compare</h2><span className="count-pill">Win, tie, or loss</span></div><div className="model-steps">{[['01','Build possible seasons','The starting point is the target NPI and Coach’s conservative .500 NESCAC case. Every open nonconference game is tested as a win, tie, or loss.'],['02','Recalculate every Division III team',`Amherst’s schedule changes its opponents’ numbers too, so all ${data.teams.length} team NPIs are recalculated together.`],['03','Show the goal, reward, and risk','Schedules are ranked by average projected NPI and show the gap to the goal, the likely range, and the downside of each opponent.']].map(([n,title,text])=><div key={n}><span>{n}</span><section><h3>{title}</h3><p>{text}</p></section></div>)}</div></section>
    <section className="panel model-card"><div className="panel-heading"><h2>NPI calculation</h2><ShieldCheck size={20}/></div><div className="model-text"><div className="formula">Game value = 15 × win + 0.85 × opponent NPI</div><p>A win above opponent NPI 54 earns an extra <strong>0.75 × (opponent NPI − 54)</strong>. A tie is evaluated as separate half-win and half-loss components.</p><p>Season aggregation is not a plain average: weak wins may be excluded after reaching ten retained win-equivalents, and losses that raise the average may be excluded. A winless team uses 85% of its lowest-rated opponent’s NPI.</p><p>{official?<>The division solver reproduces the published {data.source.season} ratings within <strong>0.001</strong>.</>:<>NPI did not exist in {data.source.season}. These ratings apply the later rules retrospectively to that season’s results.</>} Internal values are not rounded; displayed values are.</p></div></section>
    <section className="panel model-card"><div className="panel-heading"><h2>{config.target_team} by season</h2></div><div className="history-table"><div><strong>Season</strong><strong>Rating</strong><strong>Record</strong><strong>Basis</strong></div>{team?.history.map(row=><div key={row.season}><span>{row.season}</span><strong>{fmt(row.npi??undefined)}</strong><span>{row.record??'Not listed'}</span><span>{row.rating_kind==='official_npi'?'Published NPI':'Retrospective'}</span></div>)}</div></section>
    <section className="panel model-card"><div className="panel-heading"><h2>Historical data and limits</h2></div><div className="model-text"><p><strong>Selection day is the main reference point.</strong> It captures the ratings used for postseason decisions before NCAA tournament games distort the comparison. The app keeps four seasons available: two published NPI seasons and two earlier seasons reconstructed under the same rules.</p><p><strong>This is a planning estimate, not a promise.</strong> The selected season contains {data.source.eligible_npi_games.toLocaleString()} real games through {data.source.cutoff}. Rosters, travel, injuries, and an opponent’s future form are not known.</p>{data.model.method==='prior_season_out_of_time'?<p><strong>Win chances come from earlier results.</strong> The model learns from {data.model.training_seasons.join(' and ')} and checks itself against {data.model.holdout_season}. You can replace its estimate when you know a matchup better.</p>:<p><strong>This view is a historical replay.</strong> It uses that season’s final results, so it is best for learning from the past rather than predicting a future season.</p>}<p><strong>Close schedules should be treated as a tie.</strong> The low-to-high range matters more than a difference of a few hundredths. Only the leading shortlist gets the most thorough check.</p><p><strong>Scheduling availability is not known.</strong> The default opponents are examples until the real candidate list is entered.</p></div></section></div><aside><Settings config={config} onChange={onChange} onReset={onReset} disabled={disabled}/><div className="panel scale-note"><h3>NPI rating is not national rank</h3><p>This season’s NPI ratings run from <strong>{fmt(data.rating_range[0])} to {fmt(data.rating_range[1])}</strong>. A team ranked 75th does not have an NPI of 75.</p><p>Choose “Rank positions” only when you want to compare groups such as top 25, 26–50, or 51–100.</p></div></aside></div>;
}
