'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ChartNoAxesCombined, ChevronRight, CircleHelp, Layers3, LoaderCircle, ShieldCheck, SlidersHorizontal, Target, X } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarContent, SidebarFooter, SidebarHeader, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Choice, Pool, Settings, Conference } from '@/components/planning-controls';
import { Explorer } from '@/components/explorer';
import { Forecast, Results } from '@/components/results';
import { api, Bootstrap, Config, fmt, Job, Report, Validation } from '@/lib/model';

const NAV = [{id:'planner',label:'Schedule planner',icon:Layers3},{id:'explorer',label:'Opponent explorer',icon:Target},{id:'assumptions',label:'Model & assumptions',icon:SlidersHorizontal}];

export default function Home() {
  const [data,setData]=useState<Bootstrap|null>(null);
  const [season,setSeason]=useState('2025');
  const [config,setConfig]=useState<Config|null>(null);
  const [report,setReport]=useState<Report|null>(null);
  const [view,setView]=useState('planner');
  const [error,setError]=useState('');
  const [validation,setValidation]=useState<Validation|null>(null);
  const [validationError,setValidationError]=useState('');
  const [selected,setSelected]=useState(0);
  const [job,setJob]=useState<Job|null>(null);
  const [starting,setStarting]=useState(false);
  const busy=starting||job?.status==='running'||job?.status==='cancelling';
  const stale=!!report&&JSON.stringify(config)!==JSON.stringify(report.config);
  const schedule=report?.top_schedules[selected];

  useEffect(()=>{const abort=new AbortController();api<Bootstrap>(`bootstrap?season=${season}`,undefined,abort.signal).then(d=>{setData(d);setConfig(d.config);setReport(d.report);setJob(null);setSelected(0);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[season]);
  useEffect(()=>{if(!config)return;const abort=new AbortController();setValidation(null);const timer=setTimeout(()=>api<Validation>('validate',config,abort.signal).then(v=>{setValidation(v);setValidationError('');}).catch(e=>{if(e.name!=='AbortError')setValidationError(e.message);}),200);return()=>{clearTimeout(timer);abort.abort();};},[config]);
  useEffect(()=>{
    if(!job?.id||!['running','cancelling'].includes(job.status))return;
    let disposed=false;let timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{try{const next=await api<Job>(`jobs/${job.id}`);if(disposed)return;setJob(next);if(next.status==='complete'&&next.report){setReport(next.report);setSelected(0);setError('');}else if(next.status==='error'){setError(next.message);}else if(['running','cancelling'].includes(next.status)){timer=setTimeout(poll,1200);}}catch(e){if(disposed)return;const message=(e as Error).message;if(message.includes('not found')){setJob(null);setError('The app restarted and this comparison is no longer available. Your current inputs are still here.');}else{setError('The model connection was interrupted. Retrying; your inputs are unchanged.');timer=setTimeout(poll,3000);}}};
    timer=setTimeout(poll,300);return()=>{disposed=true;clearTimeout(timer);};
  },[job?.id,job?.status]);

  async function start(){if(!config||busy)throw new Error('A comparison is already running or inputs are not ready.');setStarting(true);setError('');try{const result=await api<{id:string}>('jobs',config);setJob({id:result.id,status:'running',message:'Preparing the full division…',progress:0,config});setView('planner');return result;}catch(e){setError((e as Error).message);throw e;}finally{setStarting(false);}}
  function changeSeason(next:string){setData(null);setValidation(null);setReport(null);setError('');setSeason(next);}

  const heading=view==='planner'?['Schedule planner','Choose opponents and compare projected season NPI.']:view==='explorer'?['Opponent explorer','Check the effect of a win, tie, or loss against an opponent.']:['Model & assumptions','Calculation rules, source data, and forecast limitations.'];
  return <SidebarProvider style={{'--sidebar-width':'226px'} as React.CSSProperties}>
    <Sidebar className="brand-sidebar"><SidebarHeader className="brand-head"><div className="brand-symbol"><ChartNoAxesCombined size={23}/></div><div><strong>Schedule Lab</strong><span>COLLEGIATE SOCCER</span></div></SidebarHeader><SidebarContent><div className="program"><div className="monogram">A</div><div><strong>Amherst</strong><span>Men’s soccer · Division III</span></div></div><p className="nav-label">WORKSPACE</p><SidebarMenu>{NAV.map(({id,label,icon:Icon})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>setView(id)}><Icon/><span>{label}</span>{view===id&&<ChevronRight className="ml-auto"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="verified"><ShieldCheck size={18}/><div><strong>{data?.source.rating_kind==='official_npi'?'Published NPI verified':'Historical reconstruction'}</strong><span>{data?`${data.teams.length} teams · ${data.source.season} data`:'Loading season data'}</span></div></div><div className="local-label"><span/>{data?.deployment?.hosted?'Hosted on Render':'Private, on this computer'}</div></SidebarFooter></Sidebar>
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-trigger"/><span>Workspace</span><ChevronRight size={14}/><strong>{NAV.find(n=>n.id===view)?.label}</strong></div><div className="season-control"><span>Dataset</span><Choice label="Dataset season" value={season} disabled={busy} onChange={changeSeason} options={[{value:'2025',label:'2025 selections'},{value:'2024',label:'2024 comparison'},{value:'2023',label:'2023 retrospective'},{value:'2022',label:'2022 retrospective'}]}/></div></header>
      <main className="main-content"><div className="page-heading"><div><p className="eyebrow">AMHERST MEN’S SOCCER</p><h1>{heading[0]}</h1><p>{heading[1]}</p></div>{view==='planner'&&<Button className="primary-action" disabled={!config||!validation||busy} onClick={()=>void start().catch(()=>{})}>{busy?<><LoaderCircle size={17} className="spin"/>Comparing…</>:<>Compare {validation?.combinations??''} schedules<ArrowUpRight size={18}/></>}</Button>}</div>
      {error&&<div className="notice error" role="alert">{error}{!data&&<Button variant="outline" onClick={()=>window.location.reload()}>Reconnect</Button>}</div>}
      {!data||!config?<div className="loading-state"><LoaderCircle className="spin"/><h2>Connecting to the division model</h2><p>The verified historical data will appear here shortly.</p></div>:<>
        {job&&['running','cancelling'].includes(job.status)&&<div className="job-panel" role="status" aria-live="polite"><div><LoaderCircle size={18} className="spin"/><strong>{job.status==='cancelling'?'Stopping the comparison':`Recalculating all ${data.teams.length} teams`}</strong><Button variant="ghost" disabled={job.status==='cancelling'} onClick={()=>api<Job>(`jobs/${job.id}/cancel`,{}).then(setJob).catch(e=>setError(e.message))}><X size={14}/>Cancel</Button></div><Progress aria-label="Schedule comparison progress" value={job.progress*100}/><p>{job.message}</p></div>}
        {job?.status==='cancelled'&&<div className="notice neutral" role="status">Comparison cancelled. Your previous results and current inputs are unchanged.</div>}
        {view==='planner'&&<>{data.deployment?.hosted&&<div className="notice neutral">Shared demo: one comparison at a time. Start with Quick exploration; larger runs can take several minutes. Inputs are processed on the server and results stay in this browser session. Export anything you want to keep.</div>}
          <div className="metrics"><div className="metric"><span>FIXED CONFERENCE SLATE</span><div>{config.fixed_games.length}<small>games</small></div><p>{config.fixed_games.filter(g=>g.result).length} results locked · remaining outcomes open</p></div><div className="metric"><span>NONCONFERENCE OPPORTUNITIES</span><div>{String(config.open_slots).padStart(2,'0')}<small>open slots</small></div><p>{validation?.candidate_count??'—'} candidates · {config.required.length} must-play opponents</p></div><div className={`metric ${stale?'old-metric':''}`}><span>{stale?'PREVIOUS LEADING ESTIMATE':'LEADING PROJECTED NPI'}</span><div>{fmt(report?.top_schedules[0]?.projection.mean)}<ArrowUpRight className="positive" size={22}/></div><p>{report?`${report.config.validation_samples} validation draws · ${stale?'rerun for new inputs':'historical planning replay'}`:'Run a comparison to get a projection'}</p></div></div>
          {stale&&<div className="stale-note" role="status"><CircleHelp size={16}/><span>Inputs have changed. The displayed projections belong to your previous comparison.</span></div>}
          <div className="planning-grid"><div className="main-stack"><Pool data={data} config={config} validation={validation} onChange={setConfig} disabled={busy}/><Conference config={config} onChange={setConfig} disabled={busy}/>{validationError&&<div className="notice error" role="alert">{validationError}</div>}</div><aside className="side-stack"><Settings config={config} onChange={setConfig} onReset={()=>{setConfig(data.config);setValidationError('');}} disabled={busy}/><Explorer config={config} data={data} compact/><Forecast schedule={schedule} stale={stale}/></aside></div>
          {report?<Results report={report} selected={selected} onSelect={setSelected} stale={stale}/>:<div className="panel empty-results"><ChartNoAxesCombined size={30}/><h2>No comparison yet</h2><p>Choose an opponent pool and run the model to see your leading schedules.</p></div>}
        </>}
        {view==='explorer'&&<><Explorer config={config} data={data}/><div className="explorer-bottom"><Conference config={config} onChange={setConfig} disabled={busy}/><div className="panel teaching-note"><CircleHelp size={22}/><div><h3>Why can a win hurt?</h3><p>Below ten retained win-equivalents, a low-value win still counts and can lower the average. Once the minimum is met, a weak additional win can be excluded. That’s why the same opponent can help one slate and hurt another.</p></div></div></div></>}
        {view==='assumptions'&&<ModelNotes data={data} config={config} onChange={setConfig} onReset={()=>setConfig(data.config)} disabled={busy}/>}
      </>}
      </main><footer className="app-footer">NPI Schedule Lab<span>Historical reference · Full-precision calculations · {data?.deployment?.hosted?'Hosted on Render':'Local only'}</span></footer>
    </div>
  </SidebarProvider>;
}

function ModelNotes({data,config,onChange,onReset,disabled}:{data:Bootstrap;config:Config;onChange:(c:Config)=>void;onReset:()=>void;disabled:boolean}){
  const official=data.source.rating_kind==='official_npi'; const team=data.teams.find(t=>t.name===config.target_team);
  return <div className="model-grid"><div className="main-stack"><section className="panel model-card"><div className="panel-heading"><h2>How a comparison works</h2><span className="count-pill">No averaged outcomes</span></div><div className="model-steps">{[['01','Draw a possible season','Each unlocked game becomes a win, tie, or loss using the chosen probabilities.'],['02','Recalculate the division',`Replace Amherst’s games on both sides, then converge all ${data.teams.length} team ratings simultaneously.`],['03','Compare the resulting seasons','Average the converged NPIs and show the spread. Fresh draws check the leading schedules.']].map(([n,title,text])=><div key={n}><span>{n}</span><section><h3>{title}</h3><p>{text}</p></section></div>)}</div></section>
    <section className="panel model-card"><div className="panel-heading"><h2>NPI calculation</h2><ShieldCheck size={20}/></div><div className="model-text"><div className="formula">Game value = 15 × win + 0.85 × opponent NPI</div><p>A win above opponent NPI 54 earns an extra <strong>0.75 × (opponent NPI − 54)</strong>. A tie is evaluated as separate half-win and half-loss components.</p><p>Season aggregation is not a plain average: weak wins may be excluded after reaching ten retained win-equivalents, and losses that raise the average may be excluded. A winless team uses 85% of its lowest-rated opponent’s NPI.</p><p>{official?<>The division solver reproduces the published {data.source.season} ratings within <strong>0.001</strong>.</>:<>NPI did not exist in {data.source.season}. These ratings apply the later rules retrospectively to that season’s results.</>} Internal values are not rounded; displayed values are.</p></div></section>
    <section className="panel model-card"><div className="panel-heading"><h2>{config.target_team} by season</h2></div><div className="history-table"><div><strong>Season</strong><strong>Rating</strong><strong>Record</strong><strong>Basis</strong></div>{team?.history.map(row=><div key={row.season}><span>{row.season}</span><strong>{fmt(row.npi??undefined)}</strong><span>{row.record??'Not listed'}</span><span>{row.rating_kind==='official_npi'?'Published NPI':'Retrospective'}</span></div>)}</div></section>
    <section className="panel model-card"><div className="panel-heading"><h2>Forecast limitations</h2></div><div className="model-text"><p><strong>The selected graph is a historical snapshot.</strong> It contains {data.source.eligible_npi_games.toLocaleString()} real games through {data.source.cutoff}. Other teams’ results stay fixed; rosters, travel, injuries, and future schedules are not modeled.</p>{data.model.method==='prior_season_out_of_time'?<p><strong>Pregame probabilities use prior-season ratings.</strong> The fit uses {data.model.training_seasons.join(' and ')} outcomes and holds out {data.model.holdout_season}. Holdout log loss is {fmt(data.model_diagnostics?.holdout_log_loss,4)}, versus {fmt(data.model_diagnostics?.recent_only_holdout_log_loss,4)} using only the latest training year and {fmt(data.model_diagnostics?.constant_holdout_log_loss,4)} without team strength. Lower is better.</p>:<p><strong>Pregame probabilities are retrospective for this view.</strong> End-period ratings include the same outcomes being modeled, so use this season for comparison rather than prospective calibration.</p>}<p><strong>Recent NPI changes probabilities, not the fixed point.</strong> Updated division results are needed for a genuinely new season projection.</p><p><strong>P10–P90 is season variability.</strong> Sampling error describes uncertainty in the simulated mean, not uncertainty in the model itself. Close rankings are not a proven optimum; only the leading shortlist gets independent validation.</p><p><strong>Availability is unconfirmed.</strong> The default pool is illustrative. Bands select real representative profiles.</p></div></section></div><aside><Settings config={config} onChange={onChange} onReset={onReset} disabled={disabled}/><div className="panel scale-note"><h3>Rating ≠ rank</h3><p>This dataset’s NPI ratings run from <strong>{fmt(data.rating_range[0])} to {fmt(data.rating_range[1])}</strong>. A team ranked 75th does not have an NPI of 75.</p><p>Use “Rank positions” for ordinal bands. Rating bands outside the observed range can show arithmetic, but lack historical graph profiles.</p></div></aside></div>;
}
